import Footer from "./components/Footer";
import Nav from "./components/Nav";
import "./globals.css";

export const metadata = {
  title: "Swiftbuy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='m-3 p-3'>
        <Nav />
        {children}
        <Footer />
        </body>
    </html>
  );
}
